#ifndef MAIN_MANAGER_INFRASTRUCTURE_PLAYERS_INPUT_INC_PLAYERS_INPUT_H
#define MAIN_MANAGER_INFRASTRUCTURE_PLAYERS_INPUT_INC_PLAYERS_INPUT_H

#include <string>

std::string InputPlayer();

#endif  // MAIN_MANAGER_INFRASTRUCTURE_PLAYERS_INPUT_INC_PLAYERS_INPUT_H