#ifndef MAIN_MANAGER_INFRASTRUCTURE_PLAYERS_INPUT_INC_PLAYERS_INPUT_H
#define MAIN_MANAGER_INFRASTRUCTURE_PLAYERS_INPUT_INC_PLAYERS_INPUT_H

#include <stdint.h>

namespace RSP {
namespace infrastructure {

uint8_t InputPlayer();

}
}  // namespace RSP

#endif  // MAIN_MANAGER_INFRASTRUCTURE_PLAYERS_INPUT_INC_PLAYERS_INPUT_H